---
name: Docker release
permissions:
  contents: read
  packages: write
on:
  workflow_call:
    inputs:
      major:
        description: Major version number
        type: number
        required: true
      minor:
        description: Minor version number
        type: number
        required: true
      patch:
        description: Patch version number
        type: number
        required: true
jobs:
  docker-release:
    name: Build and push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Login to GitHub Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:v${{ inputs.major }}.${{ inputs.minor }}.${{ inputs.patch }}
            ghcr.io/${{ github.repository }}:v${{ inputs.major }}.${{ inputs.minor }}
            ghcr.io/${{ github.repository }}:v${{ inputs.major }}
            ghcr.io/${{ github.repository }}:latest
