---
name: Linting
on:
  workflow_call:
    inputs:
      command:
        description: Build context
        type: string
        required: false
      working-directory:
        description: Working directory
        type: string
        required: false
        default: ./
jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Run command
        if: ${{ inputs.command }}
        working-directory: ${{ inputs.working-directory }}
        run: ${{ inputs.command }}
      - name: Super linter
        uses: super-linter/super-linter@v8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
